In [92]:
import pandas as pd
import numpy as np
import yfinance as yf
import talib

In [100]:
df=yf.download('AAPL', start='2020-01-01', end='2026-01-01')

[*********************100%***********************]  1 of 1 completed

In [101]:
df.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.400505  72.460769  71.156667  71.409770  135480400
2020-01-03  71.696617  72.455935  71.472439  71.629122  146322800
2020-01-06  72.267929  72.306499  70.568503  70.819201  118387200
2020-01-07  71.928062  72.533103  71.708703  72.277586  108872000
2020-01-08  73.085121  73.386438  71.631567  71.631567  132079200

In [102]:
df.iloc[1]

Price   Ticker
Close   AAPL      7.169662e+01
High    AAPL      7.245593e+01
Low     AAPL      7.147244e+01
Open    AAPL      7.162912e+01
Volume  AAPL      1.463228e+08
Name: 2020-01-03 00:00:00, dtype: float64

In [103]:
df.columns

MultiIndex([( 'Close', 'AAPL'),
            (  'High', 'AAPL'),
            (   'Low', 'AAPL'),
            (  'Open', 'AAPL'),
            ('Volume', 'AAPL')],
           names=['Price', 'Ticker'])

In [104]:
df.columns = df.columns.droplevel(1)

In [105]:
df

Price            Close        High         Low        Open     Volume
Date
2020-01-02   72.400505   72.460769   71.156667   71.409770  135480400
2020-01-03   71.696617   72.455935   71.472439   71.629122  146322800
2020-01-06   72.267929   72.306499   70.568503   70.819201  118387200
2020-01-07   71.928062   72.533103   71.708703   72.277586  108872000
2020-01-08   73.085121   73.386438   71.631567   71.631567  132079200
...                ...         ...         ...         ...        ...
2025-12-24  273.554016  275.172497  271.945536  272.085389   17910600
2025-12-26  273.144409  275.112569  272.604905  273.903708   21521800
2025-12-29  273.504089  274.103504  272.095404  272.435082   23715200
2025-12-30  272.824707  273.823772  272.025467  272.554970   22139600
2025-12-31  271.605835  273.424141  271.495952  272.804725   27293600

[1508 rows x 5 columns]

In [106]:
df.columns.name = None

In [107]:
df.columns
df.reset_index(inplace=True)

In [108]:
df.head()

        Date      Close       High        Low       Open     Volume
0 2020-01-02  72.400505  72.460769  71.156667  71.409770  135480400
1 2020-01-03  71.696617  72.455935  71.472439  71.629122  146322800
2 2020-01-06  72.267929  72.306499  70.568503  70.819201  118387200
3 2020-01-07  71.928062  72.533103  71.708703  72.277586  108872000
4 2020-01-08  73.085121  73.386438  71.631567  71.631567  132079200

In [109]:
df.shape

(1508, 6)

In [110]:
df.isnull().sum()
df = df.rename(columns={'Close':'close', 'Open':'open', 'High':'high', 'Low':'low', 'Volume':'volume'})

In [111]:
# The dataset is clean and ready for further analysis and modeling.
df['EMA3'] = talib.EMA(df['close'], timeperiod=3)

In [112]:
df

,Date,close,high,low,open,volume,EMA3
0,2020-01-02,72.400505,72.460769,71.156667,71.409770,135480400,NaN
1,2020-01-03,71.696617,72.455935,71.472439,71.629122,146322800,NaN
2,2020-01-06,72.267929,72.306499,70.568503,70.819201,118387200,72.121684
3,2020-01-07,71.928062,72.533103,71.708703,72.277586,108872000,72.024873
4,2020-01-08,73.085121,73.386438,71.631567,71.631567,132079200,72.554997
...,...,...,...,...,...,...,...
1503,2025-12-24,273.554016,275.172497,271.945536,272.085389,17910600,272.771933
1504,2025-12-26,273.144409,275.112569,272.604905,273.903708,21521800,272.958171
1505,2025-12-29,273.504089,274.103504,272.095404,272.435082,23715200,273.231130
1506,2025-12-30,272.824707,273.823772,272.025467,272.554970,22139600,273.027919
1507,2025-12-31,271.605835,273.424141,271.495952,272.804725,27293600,272.316877

In [113]:
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

In [114]:
import mplfinance as mpf

In [115]:
df

,close,high,low,open,volume,EMA3
Date,,,,,,
2020-01-02,72.400505,72.460769,71.156667,71.409770,135480400,NaN
2020-01-03,71.696617,72.455935,71.472439,71.629122,146322800,NaN
2020-01-06,72.267929,72.306499,70.568503,70.819201,118387200,72.121684
2020-01-07,71.928062,72.533103,71.708703,72.277586,108872000,72.024873
2020-01-08,73.085121,73.386438,71.631567,71.631567,132079200,72.554997
...,...,...,...,...,...,...
2025-12-24,273.554016,275.172497,271.945536,272.085389,17910600,272.771933
2025-12-26,273.144409,275.112569,272.604905,273.903708,21521800,272.958171
2025-12-29,273.504089,274.103504,272.095404,272.435082,23715200,273.231130
2025-12-30,272.824707,273.823772,272.025467,272.554970,22139600,273.027919
2025-12-31,271.605835,273.424141,271.495952,272.804725,27293600,272.316877